### PR TITLE
Card view changes and changes from Dev

### PR DESCRIPTION
**Pull request by LeftRuleMatters**
Contains changes that were necessary for the card view and some clean up as well as all the changes from Dev for proper merging.

### CODE REVIEW

**Comment by SScangeles** [comment]
clone boss-core by itself and ran mvn clean test in linux environment

`[ERROR] Failures: 
[ERROR] LoanTypeTest.test_CanConvertEnumerationToString:22 
Expecting:
 <"Unknown">
to be equal to:
 <"">
but was not.
[ERROR] Errors: 
[ERROR]   UserServiceTests.test_RegisterNewUser_RegistersUserSuccessfully:143->Object.toString:246 » NullPointer`

**Review by SScangeles — APPROVED** [review]
Public/Admin UI card features implemented at earlier date will possibly need to be refactored and tested for the changes.

**Review by DerrianH — APPROVED** [review]
LGTM

**Review by DerrianH — CHANGES_REQUESTED** [review]
merge confilcts

**Review by DerrianH — APPROVED** [review]
lgtm

**Pull request merged**
